# Generated by Django 4.0.5 on 2022-07-04 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.timezone)),
                ('severity_level', models.IntegerField(choices=[(0, 'Emergency'), (1, 'Alert'), (2, 'Critical'), (3, 'Error'), (4, 'Warning'), (5, 'Notice'), (6, 'Informational'), (7, 'Debug')])),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
