# Generated by Django 4.0.5 on 2022-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
